version: '3'

services:
    web:
        image: nginx
        build:
            context: .
            dockerfile: ./nginx/Dockerfile
        depends_on:
            - app
        ports:
            - 80:80
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ${PASSWORD}
        volumes:
            - ./postgres:/var/lib/postgresql/data
        ports:
            - 5432
    app:
        build: .
        volumes:
            - ./rails_app:/rails_app
        depends_on:
            - db
        stdin_open: true
        tty: true
